import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import Payment, RecoveryEvent
from app.ai import (
    get_diagnosis_with_fallback,
    calculate_customer_history,
    DiagnosisResult,
    diagnose_payment,
)

router = APIRouter(prefix="/api", tags=["Diagnosis"])


@router.post("/diagnose/{payment_id}")
def diagnose_failed_payment(
    payment_id: str,
    db: Session = Depends(get_db),
):
    """
    Diagnose a failed or abandoned payment.

    IMPORTANT:
    - Diagnosis is advisory only.
    - Diagnosis NEVER executes a recovery action.
    - Diagnosis NEVER changes payment status.
    - Policy and evaluation are handled separately by /api/evaluate/{payment_id}.
    """

    # ============================================================
    # 1. FIND PAYMENT
    # ============================================================

    payment = (
        db.query(Payment)
        .filter(Payment.payment_id == payment_id)
        .first()
    )

    if not payment:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Payment with ID '{payment_id}' not found.",
        )

    # ============================================================
    # 2. BUILD CUSTOMER HISTORY
    # ============================================================

    customer_history = calculate_customer_history(
        db,
        payment,
    )

    # ============================================================
    # 3. RUN AI / DETERMINISTIC DIAGNOSIS
    # ============================================================

    try:
        diagnosis: DiagnosisResult = get_diagnosis_with_fallback(
            payment,
            customer_history,
        )

    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Diagnosis engine unavailable: {str(exc)}",
        )

    # ============================================================
    # 4. CREATE AUDIT EVENT
    # ============================================================

    event_id = f"evt_diag_{uuid.uuid4().hex[:8]}"

    recovery_event = RecoveryEvent(
        event_id=event_id,
        payment_id=payment.payment_id,
        stage="diagnosed",
        reason=diagnosis.reason,
        action=diagnosis.recommended_action,
        touch_number=payment.retry_count,
        timestamp=datetime.now(timezone.utc),
        outcome=None,
        reference_id=None,
    )

    db.add(recovery_event)
    db.commit()
    db.refresh(recovery_event)

    # ============================================================
    # 5. POLICY CONTEXT NOTE
    # ============================================================

    policy_note = None

    if payment.status == "recovered":

        policy_note = (
            "Payment is already recovered. "
            "Diagnosis is recorded for audit only. "
            "Policy will block further recovery execution."
        )

    elif payment.opted_out:

        policy_note = (
            "Customer has opted out. "
            "Diagnosis is recorded for audit only. "
            "Policy will block recovery execution."
        )

    elif payment.retry_count >= 3:

        policy_note = (
            "Retry limit reached (retry_count >= 3). "
            "Diagnosis is recorded for audit only. "
            "Policy will block recovery execution."
        )

    # ============================================================
    # 6. RETURN STRUCTURED RESPONSE
    # ============================================================

    return {
        "payment_id": payment.payment_id,
        "customer_id": payment.customer_id,

        # Current payment state.
        # This MUST NOT be changed by diagnosis.
        "current_status": payment.status,

        "event_id": recovery_event.event_id,

        # Diagnosis generated by Claude or deterministic fallback.
        "diagnosis": diagnosis.model_dump(),

        # Helpful information for frontend.
        "policy_note": policy_note,

        # Explicit separation between diagnosis and recovery.
        "execution_allowed": False,
        "recovered": payment.status == "recovered",

        # Indicates that the next step is evaluation/policy.
        "next_step": (
            "already_recovered"
            if payment.status == "recovered"
            else "evaluate_policy"
        ),
    }